# Generated by Django 2.0.5 on 2019-03-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190313_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='avtive',
            new_name='active',
        ),
    ]
